parameters:
    liip_search.search_route: search
    # If search results should be restricted to one site, specify the site like this:
    # liip_search.restrict_to_site: www.liip.ch
    liip_search.restrict_to_site:
    liip_search.restrict_to_labels:
    liip_search.pager_max_head_items: 2
    liip_search.pager_max_tail_items: 2
    liip_search.pager_max_adjoining_items: 2
    liip_search.results_per_page: 10
    liip_search.restrict_by_language: false
    liip_search.translation_domain: LiipSearchBundle_search
    # The key to use in the query string to carry over the "query" search parameter
    liip_search.query_param_name: query
    # The key to use in the query string to carry over the "page" search parameter
    liip_search.page_param_name: page
