services:
    LiipGoogleSearch:
        class: Liip\SearchBundle\Search\GoogleSearch
        arguments:
            container: "@service_container"
            google_xml_search: "@LiipGoogleXMLAPISearch"
            search_pager: "@LiipSearchPager"
            results_per_page: "%liip_search.results_per_page%"
            restrict_by_language: "%liip_search.restrict_by_language%"
            translation_domain: "%liip_search.translation_domain%"

    LiipGoogleXMLAPISearch:
        class: Liip\SearchBundle\Helper\GoogleXMLSearch
        arguments:
            google_search_key: "%liip_search.google_search_key%"
            restrict_to_site:  "%liip_search.restrict_to_site%"

    LiipSearchPager:
        class: Liip\SearchBundle\Pager\Pager
        arguments:
            container: "@service_container"
            router: "@router"
            search_route: "%liip_search.search_route%"
            templating_engine: "@templating"
            max_extremity_items: "%liip_search.pager_max_extremity_items%"
            max_adjoining_items: "%liip_search.pager_max_adjoining_items%"

    liip_search_default_controller:
        class: Liip\SearchBundle\Controller\DefaultController
        scope: request
        arguments:
            container: "@service_container"
            router: "@router"
