services:
    liip_google_search:
        class: Liip\SearchBundle\Controller\GoogleSearchController
        arguments:
            google_xml_search: "@liip_google_xml_api_search"
            templating_engine: "@templating"
            results_per_page: "%liip_search.results_per_page%"
            restrict_by_language: "%liip_search.restrict_by_language%"
            translation_domain: "%liip_search.translation_domain%"
            page_param_name: "%liip_search.page_param_name%"
            query_param_name: "%liip_search.query_param_name%"
            search_route: "%liip_search.search_route%"

    liip_google_xml_api_search:
        class: Liip\SearchBundle\Google\GoogleXMLSearch
        arguments:
            google_search_key: "%liip_search.google_search_key%"
            restrict_to_site:  "%liip_search.restrict_to_site%"
            restrict_to_labels: "%liip_search.restrict_to_labels%"

    liip_search_pager:
        class: Liip\SearchBundle\Pager\Pager
        arguments:
            router: "@router"
            search_route: "%liip_search.search_route%"
            max_extremity_items: "%liip_search.pager_max_extremity_items%"
            max_adjoining_items: "%liip_search.pager_max_adjoining_items%"
            query_param_name: "%liip_search.query_param_name%"
            page_param_name: "%liip_search.page_param_name%"

    liip_search_default_controller:
        class: Liip\SearchBundle\Controller\DefaultController
        arguments:
            templating_engine: "@templating"
            router: "@router"
            pager: "@liip_search_pager"
            translation_domain: "%liip_search.translation_domain%"
            query_param_name: "%liip_search.query_param_name%"
            search_route: "%liip_search.search_route%"
